<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RootNamespace>Axlon.Services.Merchant</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Axlon.Framework.Data" />
    <PackageReference Include="Axlon.Framework.Serilog" />
    <PackageReference Include="Axlon.Framework.Authentication" />
    <PackageReference Include="Axlon.Framework.Web" />
    <PackageReference Include="Axlon.Framework.EventBus" />
    <PackageReference Include="CoordinateSharp" />
    <PackageReference Include="NGeoHash" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\aspire\AspireApp\AspireApp.ServiceDefaults\AspireApp.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Axlon.Services.Contracts\Axlon.Services.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="OutInput\" />
  </ItemGroup>

</Project>
