services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:v3.17.0
    container_name: woodpecker-server
    ports:
      - "6607:8000"
    expose:
      - "9000"
    environment:
      WOODPECKER_HOST: "${WOODPECKER_HOST}"
      WOODPECKER_OPEN: "false"
      WOODPECKER_ADMIN: "${WOODPECKER_ADMIN}"
      WOODPECKER_REPO_OWNERS: "${WOODPECKER_REPO_OWNERS}"
      WOODPECKER_GITHUB: "true"
      WOODPECKER_GITHUB_CLIENT: "${WOODPECKER_GITHUB_CLIENT}"
      WOODPECKER_GITHUB_SECRET: "${WOODPECKER_GITHUB_SECRET}"
      WOODPECKER_AGENT_SECRET: "${WOODPECKER_AGENT_SECRET}"
    volumes:
      - /www/docker/woodpecker:/var/lib/woodpecker
    restart: unless-stopped

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:v3.17.0
    container_name: woodpecker-agent
    command: agent
    depends_on:
      - woodpecker-server
    environment:
      WOODPECKER_SERVER: "woodpecker-server:9000"
      WOODPECKER_AGENT_SECRET: "${WOODPECKER_AGENT_SECRET}"
      WOODPECKER_BACKEND: "docker"
      WOODPECKER_HOSTNAME: "production-agent"
      WOODPECKER_AGENT_LABELS: "deployment=production"
      WOODPECKER_MAX_WORKFLOWS: "1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
